// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:zz
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhNEBGWC8BxxBJC109lPXvpQtzefTdiIc',
    appId: '1:916454863803:web:3aecf412e7c7f19fef8a9e',
    messagingSenderId: '916454863803',
    projectId: 'petcare-56dc6',
    authDomain: 'petcare-56dc6.firebaseapp.com',
    storageBucket: 'petcare-56dc6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPr8cTUboTXrtpfmw1eh-2k47TbPc7m40',
    appId: '1:916454863803:android:fdb39e40d7c3322bef8a9e',
    messagingSenderId: '916454863803',
    projectId: 'petcare-56dc6',
    storageBucket: 'petcare-56dc6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALdzXJR0TOpgD4QTFk7cD97z-J8DCJ47o',
    appId: '1:916454863803:ios:9dfb5e271469f072ef8a9e',
    messagingSenderId: '916454863803',
    projectId: 'petcare-56dc6',
    storageBucket: 'petcare-56dc6.firebasestorage.app',
    iosBundleId: 'com.example.proyectoBt7274',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALdzXJR0TOpgD4QTFk7cD97z-J8DCJ47o',
    appId: '1:916454863803:ios:9dfb5e271469f072ef8a9e',
    messagingSenderId: '916454863803',
    projectId: 'petcare-56dc6',
    storageBucket: 'petcare-56dc6.firebasestorage.app',
    iosBundleId: 'com.example.proyectoBt7274',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhNEBGWC8BxxBJC109lPXvpQtzefTdiIc',
    appId: '1:916454863803:web:45446aeba57a984fef8a9e',
    messagingSenderId: '916454863803',
    projectId: 'petcare-56dc6',
    authDomain: 'petcare-56dc6.firebaseapp.com',
    storageBucket: 'petcare-56dc6.firebasestorage.app',
  );
}
